schema_version: 1

context:
  name: tabpfn-common-utils
  version: "0.2.15"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tabpfn_common_utils-${{ version }}.tar.gz
  sha256: 7aeca8b8d20a188635a7d67dcd1e7d8db2fb5bb2bfe4ed5f5643d9dabba67d45

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.25
    - hatch-vcs >=0.3
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.21.6
    - pandas >=1.4.0,<3
    - scikit-learn >=1.2.0
    - typing_extensions >=4.12,<5
    - posthog >=6.7,<7.dev0
    - platformdirs >=4
    - filelock >=3.19.1
    - requests >=2.32.5
    - ruff >=0.11.6
tests:
  - python:
      imports:
        - tabpfn_common_utils
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Utilities shared between TabPFN codebases
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://priorlabs.ai

extra:
  recipe-maintainers:
    - janjagusch
